@startuml room
left to right direction

actor Guest
actor "Registered User"
actor User
actor Admin

User --|> "Registered User"
Admin --|> "Registered User"

rectangle "Room" {
    usecase "create new room" as RoomUC1
    usecase "get one room" as RoomUC2
    usecase "get all rooms" as RoomUC3
    usecase "update one room" as RoomUC4
    usecase "delete one room" as RoomUC5
    usecase "get room's unavailable times" as RoomUC6
}

Guest --> RoomUC2
Guest --> RoomUC3
Guest --> RoomUC6

"Registered User" --> RoomUC2
"Registered User" --> RoomUC3
"Registered User" --> RoomUC6

Admin --> RoomUC1
Admin --> RoomUC4
Admin --> RoomUC5

@enduml