@startuml user
left to right direction

actor "Registered User"
actor User
actor Admin

User --|> "Registered User"
Admin --|> "Registered User"

rectangle "User (Account)" {
    usecase "get me" as UserUC1
    usecase "update me" as UserUC2
    usecase "delete me" as UserUC3

    usecase "get one user" as UserUC4
    usecase "get all user" as UserUC5
    usecase "delete one user" as UserUC6
}

"Registered User" --> UserUC1

User --> UserUC2
User --> UserUC3

Admin --> UserUC4
Admin --> UserUC5
Admin --> UserUC6


@enduml